export default [
  // Disney classics
  { id: 1,  movie: 'The Lion King',           lyric: 'Simba' },
  { id: 2,  movie: 'The Lion King',           lyric: 'Mufasa' },
  { id: 3,  movie: 'The Lion King',           lyric: 'Timon' },
  { id: 4,  movie: 'The Lion King',           lyric: 'Nala' },
  { id: 5,  movie: 'The Lion King',           lyric: 'Scar' },
  { id: 6,  movie: 'Frozen',                  lyric: 'Elsa' },
  { id: 7,  movie: 'Frozen',                  lyric: 'Olaf' },
  { id: 8,  movie: 'Frozen',                  lyric: 'Sven' },
  { id: 9,  movie: 'Moana',                   lyric: 'Moana' },
  { id: 10, movie: 'Moana',                   lyric: 'Maui' },
  { id: 11, movie: 'Cinderella',              lyric: 'Cinderella' },
  { id: 12, movie: 'Sleeping Beauty',         lyric: 'Maleficent' },
  { id: 13, movie: '101 Dalmatians',          lyric: 'Cruella' },
  { id: 14, movie: 'Snow White',              lyric: 'Grumpy' },
  { id: 15, movie: 'Snow White',              lyric: 'Dopey' },
  { id: 16, movie: 'Snow White',              lyric: 'Bashful' },
  { id: 17, movie: 'Mickey Mouse',            lyric: 'Mickey' },
  { id: 18, movie: 'Mickey Mouse',            lyric: 'Minnie' },
  { id: 19, movie: 'Mickey Mouse',            lyric: 'Goofy' },
  { id: 20, movie: 'Mickey Mouse',            lyric: 'Pluto' },
  { id: 21, movie: 'DuckTales',               lyric: 'Scrooge' },
  { id: 22, movie: 'The Little Mermaid',      lyric: 'Ariel' },
  { id: 23, movie: 'The Little Mermaid',      lyric: 'Ursula' },
  { id: 24, movie: 'The Little Mermaid',      lyric: 'Sebastian' },
  { id: 25, movie: 'Aladdin',                 lyric: 'Jasmine' },
  { id: 26, movie: 'Aladdin',                 lyric: 'Jafar' },
  { id: 27, movie: 'Aladdin',                 lyric: 'Genie' },
  { id: 28, movie: 'Beauty and the Beast',    lyric: 'Gaston' },
  { id: 29, movie: 'Beauty and the Beast',    lyric: 'Lumiere' },
  { id: 30, movie: 'Mulan',                   lyric: 'Mulan' },
  { id: 31, movie: 'Mulan',                   lyric: 'Mushu' },
  { id: 32, movie: 'Tarzan',                  lyric: 'Tarzan' },
  { id: 33, movie: 'Hercules',                lyric: 'Hercules' },
  { id: 34, movie: 'Hercules',                lyric: 'Hades' },
  { id: 35, movie: 'Pinocchio',               lyric: 'Pinocchio' },
  { id: 36, movie: 'Dumbo',                   lyric: 'Dumbo' },
  { id: 37, movie: 'Bambi',                   lyric: 'Bambi' },
  { id: 38, movie: 'Winnie the Pooh',         lyric: 'Tigger' },
  { id: 39, movie: 'Winnie the Pooh',         lyric: 'Eeyore' },
  { id: 40, movie: 'Winnie the Pooh',         lyric: 'Piglet' },
  // Pixar
  { id: 41, movie: 'Toy Story',               lyric: 'Woody' },
  { id: 42, movie: 'Toy Story',               lyric: 'Buzz' },
  { id: 43, movie: 'Toy Story',               lyric: 'Lotso' },
  { id: 44, movie: 'Finding Nemo',            lyric: 'Nemo' },
  { id: 45, movie: 'Finding Nemo',            lyric: 'Dory' },
  { id: 46, movie: 'Finding Nemo',            lyric: 'Marlin' },
  { id: 47, movie: 'Finding Nemo',            lyric: 'Crush' },
  { id: 48, movie: 'The Incredibles',         lyric: 'Elastigirl' },
  { id: 49, movie: 'The Incredibles',         lyric: 'Frozone' },
  { id: 50, movie: 'The Incredibles',         lyric: 'Edna' },
  { id: 51, movie: 'Monsters Inc',            lyric: 'Sulley' },
  { id: 52, movie: 'Monsters Inc',            lyric: 'Boo' },
  { id: 53, movie: 'Ratatouille',             lyric: 'Remy' },
  { id: 54, movie: 'Ratatouille',             lyric: 'Linguini' },
  { id: 55, movie: 'WALL-E',                  lyric: 'Wall-E' },
  { id: 56, movie: 'WALL-E',                  lyric: 'Eve' },
  { id: 57, movie: 'Up',                      lyric: 'Dug' },
  { id: 58, movie: 'Up',                      lyric: 'Russell' },
  { id: 59, movie: 'Brave',                   lyric: 'Merida' },
  { id: 60, movie: 'Inside Out',              lyric: 'Bing Bong' },
  { id: 61, movie: 'Inside Out',              lyric: 'Joy' },
  { id: 62, movie: 'Inside Out',              lyric: 'Sadness' },
  { id: 63, movie: 'Inside Out',              lyric: 'Disgust' },
  { id: 64, movie: 'Coco',                    lyric: 'Miguel' },
  { id: 65, movie: 'Coco',                    lyric: 'Hector' },
  { id: 66, movie: 'Encanto',                 lyric: 'Mirabel' },
  { id: 67, movie: 'Encanto',                 lyric: 'Luisa' },
  { id: 68, movie: 'Encanto',                 lyric: 'Bruno' },
  { id: 69, movie: 'Luca',                    lyric: 'Luca' },
  { id: 70, movie: 'Turning Red',             lyric: 'Meilin' },
  // DreamWorks
  { id: 71, movie: 'Shrek',                   lyric: 'Shrek' },
  { id: 72, movie: 'Shrek',                   lyric: 'Fiona' },
  { id: 73, movie: 'Shrek',                   lyric: 'Donkey' },
  { id: 74, movie: 'Shrek',                   lyric: 'Gingy' },
  { id: 75, movie: 'Kung Fu Panda',           lyric: 'Po' },
  { id: 76, movie: 'Kung Fu Panda',           lyric: 'Tigress' },
  { id: 77, movie: 'Kung Fu Panda',           lyric: 'Shifu' },
  { id: 78, movie: 'Kung Fu Panda',           lyric: 'Oogway' },
  { id: 79, movie: 'Madagascar',              lyric: 'Melman' },
  { id: 80, movie: 'Madagascar',              lyric: 'Gloria' },
  { id: 81, movie: 'How to Train Your Dragon', lyric: 'Hiccup' },
  { id: 82, movie: 'How to Train Your Dragon', lyric: 'Toothless' },
  { id: 83, movie: 'Trolls',                  lyric: 'Poppy' },
  { id: 84, movie: 'Trolls',                  lyric: 'Branch' },
  // Universal / Illumination
  { id: 85, movie: 'Despicable Me',           lyric: 'Gru' },
  { id: 86, movie: 'Despicable Me',           lyric: 'Vector' },
  { id: 87, movie: 'The Lorax',               lyric: 'Lorax' },
  { id: 88, movie: 'Sing',                    lyric: 'Buster' },
]
