export default [
  { id: 1,  movie: 'The Lion King',          lyric: 'Simba' },
  { id: 2,  movie: 'The Lion King',          lyric: 'Mufasa' },
  { id: 3,  movie: 'The Lion King',          lyric: 'Timon' },
  { id: 4,  movie: 'The Lion King',          lyric: 'Pumbaa' },
  { id: 5,  movie: 'The Lion King',          lyric: 'Nala' },
  { id: 6,  movie: 'Frozen',                 lyric: 'Elsa' },
  { id: 7,  movie: 'Frozen',                 lyric: 'Olaf' },
  { id: 8,  movie: 'Moana',                  lyric: 'Moana' },
  { id: 9,  movie: 'Moana',                  lyric: 'Maui' },
  { id: 10, movie: 'Cinderella',             lyric: 'Cinderella' },
  { id: 11, movie: 'Sleeping Beauty',        lyric: 'Maleficent' },
  { id: 12, movie: '101 Dalmatians',         lyric: 'Cruella De Vil' },
  { id: 13, movie: 'Snow White',             lyric: 'Snow White' },
  { id: 14, movie: 'Mickey Mouse',           lyric: 'Mickey Mouse' },
  { id: 15, movie: 'DuckTales',              lyric: 'Donald Duck' },
  { id: 16, movie: 'Toy Story',              lyric: 'Buzz Lightyear' },
  { id: 17, movie: 'Toy Story',              lyric: 'Woody' },
  { id: 18, movie: 'Winnie the Pooh',        lyric: 'Winnie the Pooh' },
  { id: 19, movie: 'The Little Mermaid',     lyric: 'Ariel' },
  { id: 20, movie: 'Beauty and the Beast',   lyric: 'Gaston' },
]
